version: '3.8'

services:
  userdb:
    image: postgres:15
    container_name: user_db
    environment:
      POSTGRES_DB: ${POSTGRES_USER_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_USER_PORT}:5432"
    volumes:
      - postgres_data_user:/var/lib/postgresql/data

  roledb:
    image: postgres:15
    container_name: role_db
    environment:
      POSTGRES_DB: ${POSTGRES_ROLE_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_ROLE_PORT}:5432"
    volumes:
      - postgres_data_role:/var/lib/postgresql/data

volumes:
  postgres_data_user:
  postgres_data_role:
