spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: role-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_ROLE_PORT}/${POSTGRES_ROLE_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/db.changelog.yml
    enabled: true
server:
  forward-headers-strategy: framework
  port: 0
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
