spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://userdb:${POSTGRES_USER_PORT}/${POSTGRES_USER_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/db.changelog.yml
    enabled: true
server:
  forward-headers-strategy: framework
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
