spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  config:
    name: userservice
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka