spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: eureka
server:
  port: ${EUREKA_SERVER_PORT}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
